# <center>Final Project (Part 3.1)</center>
### <center>Group 50</center>
### <center>Zian He, Junsong yao</center>
<center>2022/11/15</center>

## 1. Load & process data

In [1]:
# import all the packages I need
import pandas as pd
import numpy as np
import altair as alt
import matplotlib.pyplot as plt

In [2]:
myJekyllSaveDir = '/Users/silver/Downloads/'

In [3]:
data_url = 'https://data.illinois.gov/dataset/3bfc782a-baae-43ea-a29a-214fb1cb725e/resource/b23aa1b9-c0e0-4779-ba7a-6ca8b7b1df1c/download/cm_offense_archive.csv'
data = pd.read_csv(data_url)
data.columns

Index(['CaseNo', 'Description', 'Occurred Date', 'Occurred Day of Week',
       'Occurred Time', 'X', 'Y', 'Crime Against Code', 'Crime Against',
       'Group', 'Beat', 'Ward'],
      dtype='object')

In [4]:
data

,CaseNo,Description,Occurred Date,Occurred Day of Week,Occurred Time,X,Y,Crime Against Code,Crime Against,Group,Beat,Ward
0,16-009615,90C - Disorderly Conduct,20160125,1,1006,-89.124354,42.284104,NaN,NaN,NaN,NaN,7.0
1,16-014351,90C - Disorderly Conduct,20160205,5,1906,-89.070417,42.254735,NaN,NaN,NaN,NaN,11.0
2,16-016247,13B - Simple Assault,20160209,2,1550,-89.042083,42.238147,NaN,NaN,NaN,NaN,8.0
3,16-016181,290 - Destruction/Damage/Vandalism of Property,20160210,3,1138,-89.029085,42.241433,NaN,NaN,NaN,NaN,14.0
4,16-023111,23H - All Other Larceny,20160206,6,100,-89.029201,42.211097,NaN,NaN,NaN,NaN,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...
200638,20-087026,90C - Disorderly Conduct,20200807,5,1430,-89.131835,42.276667,SO,SOCIETY,B,RP04,13.0
200639,20-086961,23C - Shoplifting,20200807,5,1241,-89.086349,42.250115,PR,PROPERTY,A,RP06,11.0
200640,20-087240,290 - Destruction/Damage/Vandalism of Property,20200807,5,2318,-88.966168,42.273391,PR,PROPERTY,A,RP10,1.0
200641,20-087240,13A - Aggravated Assault,20200807,5,2318,-88.966168,42.273391,PE,PERSON,A,RP10,1.0
200642,20-087212,90C - Disorderly Conduct,20200807,5,2145,-89.063908,42.221579,SO,SOCIETY,B,RP07,6.0

In [5]:
data.head()

,CaseNo,Description,Occurred Date,Occurred Day of Week,Occurred Time,X,Y,Crime Against Code,Crime Against,Group,Beat,Ward
0,16-009615,90C - Disorderly Conduct,20160125,1,1006,-89.124354,42.284104,NaN,NaN,NaN,NaN,7.0
1,16-014351,90C - Disorderly Conduct,20160205,5,1906,-89.070417,42.254735,NaN,NaN,NaN,NaN,11.0
2,16-016247,13B - Simple Assault,20160209,2,1550,-89.042083,42.238147,NaN,NaN,NaN,NaN,8.0
3,16-016181,290 - Destruction/Damage/Vandalism of Property,20160210,3,1138,-89.029085,42.241433,NaN,NaN,NaN,NaN,14.0
4,16-023111,23H - All Other Larceny,20160206,6,100,-89.029201,42.211097,NaN,NaN,NaN,NaN,14.0

In [6]:
crime_data = data[(data["Crime Against"]=='SOCIETY')|(data["Crime Against"]=='PROPERTY')|(data["Crime Against"]=='PERSON')]

In [7]:
crime_data["Crime Against"]

20        PROPERTY
34        PROPERTY
51        PROPERTY
52          PERSON
53          PERSON
            ...
200638     SOCIETY
200639    PROPERTY
200640    PROPERTY
200641      PERSON
200642     SOCIETY
Name: Crime Against, Length: 200594, dtype: object

In [8]:
alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('default')

## 2. Create dashboard

```python
brush = alt.selection_interval(encodings=['x','y'])

rect_alt = alt.Chart(crime_data).mark_rect().encode(
    alt.X("Crime Against:O"),
    alt.Y("Occurred Day of Week:O"),
    alt.Color("count()")
).properties(
    height=400
).add_selection(
    brush
)

hist_alt = alt.Chart(crime_data).mark_bar().encode(
    alt.X("Occurred Time:Q",bin=True, axis=alt.Axis(title='Occurred Time')),
    alt.Y("count()", axis=alt.Axis(title='Frequency'))
).transform_filter(
    brush
)

dashboard_local = rect_alt.properties(width=300) | hist_alt.properties(width=300)

dashboard_local.save(myJekyllSaveDir+'Final3.1.json')
```

### 3.1 Dashboard describe

We created a visualization of the average number of wards of different types of crime objects for each day of the week in this city. As well as the distribution of the time of occurrence of different crime objects for each day of the week. We first created a heatmap with the x-axis of the visualization being the three types of crime objects (Person, Property, Society) and the y-axis being each day of the week. The color of the heatmap then represents the difference in the average number of victims. We link this heatmap to a bar chart. This allows us to see the number of different crime times occurring at that average ward number by selecting a different average ward number. This dashboard allows the layperson to understand the average number of wards, or victims, for each day of the week,what type of crimes these victims were subjected to, as well as the distribution of when these crimes occurred.

### 3.2 contextual datasets

Police Arrests Upload Datasets: https://data.illinois.gov/dataset/1d18ecc0-3c7e-4507-b8cc-7a5e30359d44/resource/ca1dceb3-01f8-4a56-935b-7e3035ff60a4/download/police-arrests-upload_20191226.csv

The contextual data we found were police arrest data for Urbana. This data has the same clear documentation of crimes in Urbana as the City of Rockford crime records that we used. And we found some very interesting elements on this data, such as the age, gender, and race of the arrestees. We think these variables can help us to analyze and predict the motives and trends of crime by combining or comparing the two data visualizations.

In [9]:
d_url = 'https://data.illinois.gov/dataset/1d18ecc0-3c7e-4507-b8cc-7a5e30359d44/resource/ca1dceb3-01f8-4a56-935b-7e3035ff60a4/download/police-arrests-upload_20191226.csv'
df = pd.read_csv(d_url)

In [10]:
df.head(10)

,arrest_code,incident_number,date_of_arrest,year_of_arrest,month_of_arrest,arrest_type_description,crime_code,crime_code_description,crime_category_code,crime_category_description,...,age_at_arrest,arrestee_sex,arrestee_race,arrestee_employment_description,arrestee_residency_description,arrestee_home_city,arrestee_home_state,arrestee_home_zip,arrest_resolution,mapped_address
0,A00-00005,U00-00050,01/04/2000,2000,1,ON VIEW,4387,VIOLATION ORDER PROTECTION,C85,Violation Ord Protect/No Cont,...,43.0,FEMALE,WHITE,EMPLOYED,NON-RESIDENT,NaN,NaN,00000,TAKEN TO JAIL,NaN
1,A00-00009,U00-00075,01/04/2000,2000,1,WARRANT ARREST,5081,WARRANT-IN STATE,C86,Warrants & Summons,...,28.0,MALE,WHITE,UNEMPLOYED,RESIDENT,NaN,NaN,00000,TAKEN TO JAIL,NaN
2,A00-00010,U00-00075,01/04/2000,2000,1,WARRANT ARREST,5081,WARRANT-IN STATE,C86,Warrants & Summons,...,28.0,MALE,WHITE,UNEMPLOYED,RESIDENT,NaN,NaN,00000,TAKEN TO JAIL,NaN
3,A00-00046,U00-00015,01/01/2000,2000,1,ON VIEW,6630,DRIVING WITHOUT LIGHTS,C28,Traffic Offenses,...,19.0,MALE,WHITE,EMPLOYED,NON-RESIDENT,NaN,NaN,00000,TAKEN TO JAIL,NaN
4,A00-00047,U00-00015,01/01/2000,2000,1,ON VIEW,2410,DRIVING UNDER THE INFL-ALCOHOL,C69,Driving Under the Influence,...,19.0,MALE,WHITE,EMPLOYED,NON-RESIDENT,NaN,NaN,00000,TAKEN TO JAIL,NaN
5,A00-00048,U00-00015,01/01/2000,2000,1,ON VIEW,2415,BREATH ALCOHOL OVER LIMIT,C69,Driving Under the Influence,...,19.0,MALE,WHITE,EMPLOYED,NON-RESIDENT,NaN,NaN,00000,TAKEN TO JAIL,NaN
6,A00-00060,U00-00026,01/02/2000,2000,1,ON VIEW,1330,TRESPASS TO LAND/REAL PROPERTY,C77,Trespassing,...,46.0,MALE,BLACK,EMPLOYED,NON-RESIDENT,NaN,NaN,00000,TAKEN TO JAIL,NaN
7,A00-00083,U00-00054,01/04/2000,2000,1,ON VIEW,2470,NO DRIVERS LICENSE,C28,Traffic Offenses,...,26.0,MALE,WHITE,UNKNOWN,NON-RESIDENT,NaN,NaN,00000,TAKEN TO JAIL,NaN
8,A00-00084,U00-00055,01/04/2000,2000,1,ON VIEW,2480,SUSPEND REVOKED DRIVERS LICENSE,C28,Traffic Offenses,...,60.0,MALE,BLACK,UNKNOWN,RESIDENT,NaN,NaN,00000,TAKEN TO JAIL,NaN
9,A00-00085,U00-00055,01/04/2000,2000,1,ON VIEW,2461,OPERATE UNINSURED MOTOR VEHICLE,C28,Traffic Offenses,...,60.0,MALE,BLACK,UNKNOWN,RESIDENT,NaN,NaN,00000,TAKEN TO JAIL,NaN